[project]
name = "memestack-contracts"
description = "A memecoin launchpad on Stacks with STX as base token"
authors = []
telemetry = false
cache_dir = "./.cache"
requirements = []

[contracts.memecoin-launchpad]
path = "contracts/memecoin-launchpad.clar"
clarity_version = 2
epoch = 2.5

[contracts.sip-010-trait]
path = "contracts/sip-010-trait.clar"
clarity_version = 2
epoch = 2.5

[contracts.token-factory]
path = "contracts/token-factory.clar"
clarity_version = 2
epoch = 2.5

[contracts.memecoin-token]
path = "contracts/memecoin-token.clar"
clarity_version = 2
epoch = 2.5

[repl.analysis]
passes = ["check_checker"]

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
